### ISSUE TITLE
Feedback: Tests

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/ssgkmeansr#30]
As far as I can tell, your tests are only checking for bad input. But what about good input? It's crucial that you not only test that your functions can handle bad data, but that they also return the correct answers.  You can use another package as a benchmark if you don't want to compute the clusters by hand.

**Comment by xiaosophiameng** [comment]
Hi Vaden, 

We are confused by this feedback because we tested on both good and bad input.  And for each of the test script, we almost the same weight of testing on good input and bad input. 

For example (in our "fit test script"),

  # Expected outputs:
  expect_equal(typeof(result), "list")
  expect_equal(length(result), 3)
  expect_equal(is.data.frame(result[[1]]), TRUE)
  expect_equal(typeof(result[[2]]), "double")
  expect_equal(result[[2]]>0, TRUE)
  expect_equal(is.data.frame(result[[3]]), TRUE)
  
})

test_that('Error in input data', {
  # expected error:
  expect_error(fit(data_bad_string), 'Input data must be numeric')
  expect_error(fit(data_bad_1d), 'Input data must have 2 columns')
  expect_error(fit(data_bad_empty), 'Input data cannot be empty')
})
